# Generated by Django 5.1.3 on 2024-11-10 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvariation',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemVariations', related_query_name='ItemVariations', to='App_Ecommerce.items'),
        ),
    ]
