# Generated by Django 5.1.3 on 2024-12-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Ecommerce', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='discount_price',
            new_name='price',
        ),
    ]
