# Generated by Django 5.1.3 on 2024-11-12 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Ecommerce', '0002_alter_itemvariation_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvariation',
            name='AttributeTerm',
        ),
        migrations.AddField(
            model_name='items',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='items',
            name='product_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemvariation',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color_variations', to='App_Ecommerce.attributeterm'),
        ),
        migrations.AddField(
            model_name='itemvariation',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='itemvariation',
            name='product_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemvariation',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='size_variations', to='App_Ecommerce.attributeterm'),
        ),
    ]
